name       : x265
version    : 2.0
release    : 1
source     :
    - https://bitbucket.org/multicoreware/x265/downloads/x265_2.0.tar.gz : 5a7f6797bee33310c690be5d9a6c63125f36663ac3478e98ac6b6142a70bce1f
license    : GPL-2.0
component  : multimedia.codecs
summary    : x265 is an open source HEVC encoder.
description: |
    x265 is an open source HEVC encoder.
builddeps  :
    - yasm
setup      : |
    cd source
    %cmake -DENABLED_SHARED=ON -DLIB_INSTALL_DIR=lib64 -DSTATIC_LINK_CRT=OFF .
build      : |
    cd source
    %make
install    : |
    cd source
    %make_install
    rm $installdir/%libdir%/libx265.a
