name       : x265
version    : '3.4'
release    : 17
source     :
    - https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz : c2047f23a6b729e5c70280d23223cb61b57bfe4ad4e8f1471eeee2a61d148672
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : x265 is an open source HEVC encoder
description: |
    The primary objective of x265 is to become the best H.265/HEVC encoder available anywhere, offering the highest compression efficiency and the highest performance on a wide variety of hardware platforms.
optimize   :
    - no-symbolic
build      : |
    cd source
    mkdir build-8bit build-10bit build-12bit

    # Build 12-bit color depth
    pushd build-12bit
    %cmake \
        -DENABLE_CLI='FALSE' \
        -DEXPORT_C_API='FALSE' \
        -DHIGH_BIT_DEPTH='TRUE'\
        -DLIB_INSTALL_DIR=lib64 \
        -DMAIN12='TRUE' \
        -DENABLE_SHARED='FALSE' \
        -DEXTRA_LINK_FLAGS=${LDFLAGS} \
        ..
    %make
    popd

    # Build 10-bit color depth
    pushd build-10bit
    %cmake \
        -DENABLE_CLI='FALSE' \
        -DEXPORT_C_API='FALSE' \
        -DHIGH_BIT_DEPTH='TRUE'\
        -DLIB_INSTALL_DIR=lib64 \
        -DENABLE_SHARED='FALSE' \
        -DEXTRA_LINK_FLAGS=${LDFLAGS} \
        ..
    %make
    popd

    # Build 8-bit color depth
    pushd build-8bit
    ln -s ../build-10bit/libx265.a libx265_main10.a
    ln -s ../build-12bit/libx265.a libx265_main12.a
    %cmake \
        -DEXTRA_LIB='x265_main10.a;x265_main12.a' \
        -DEXTRA_LINK_FLAGS="${LDFLAGS} -L ." \
        -DLIB_INSTALL_DIR=lib64 \
        -DLINKED_10BIT='TRUE' \
        -DLINKED_12BIT='TRUE' \
        -DENABLE_SHARED='TRUE' \
        ..
    %make
    popd
install    : |
    cd source/build-8bit
    %make_install
    # Note, we package .a files because 8-bit needs to statically compile against 10 and 12 bit
