name       : x265
version    : '2.6'
release    : 8
source     :
    - https://bitbucket.org/multicoreware/x265/downloads/x265_2.6.tar.gz : 1bf0036415996af841884802161065b9e6be74f5f6808ac04831363e2549cdbf
license    : GPL-2.0
component  : multimedia.codecs
summary    : x265 is an open source HEVC encoder.
description: |
    x265 is an open source HEVC encoder.
builddeps  :
    - yasm
build      : |
    cd source
    mkdir build-8bit build-10bit build-12bit
    # Build 12-bit color depth
    pushd build-12bit
    %cmake -DENABLED_SHARED='FALSE' \
        -DENABLE_CLI='FALSE' \
        -DEXPORT_C_API='FALSE' \
        -DHIGH_BIT_DEPTH='TRUE'\
        -DLIB_INSTALL_DIR=lib64 \
        -DMAIN12='TRUE' \
        -DENABLE_ASSEMBLY=FALSE \
        ..
    %make
    popd
    # Build 10-bit color depth
    pushd build-10bit
    %cmake -DENABLED_SHARED='FALSE' \
        -DENABLE_CLI='FALSE' \
        -DEXPORT_C_API='FALSE' \
        -DHIGH_BIT_DEPTH='TRUE'\
        -DLIB_INSTALL_DIR=lib64 \
        -DENABLE_ASSEMBLY=FALSE \
        ..
    %make
    popd
    # Build 8-bit color depth
    pushd build-8bit
    ln -s ../build-10bit/libx265.a libx265_main10.a
    ln -s ../build-12bit/libx265.a libx265_main12.a
    %cmake -DENABLED_SHARED='TRUE' \
        -DEXTRA_LIB='x265_main10.a;x265_main12.a' \
        -DEXTRA_LINK_FLAGS='-L.' \
        -DLIB_INSTALL_DIR=lib64 \
        -DLINKED_10BIT='TRUE' \
        -DLINKED_12BIT='TRUE' \
        -DENABLE_ASSEMBLY=FALSE \
        ..
    %make
    popd
install    : |
    cd source/build-8bit
    %make_install
    # Note, we package .a files because 8-bit needs to statically compile against 10 and 12 bit
